#!/bin/bash
get_packages() { adb shell pm list packages -e | sort -t";" -k2 | sed 's/package:/FALSE\n/g' | sed s/\\r\$//; }
os_version() { adb shell getprop ro.build.version.release | sed s/\\r\$//; }
select_packages_block() { yad --list --checklist --column "Block" --column "Package" --separator "" --print-column=2 --width=600 --height=400; }
select_packages_unblock() { yad --list --checklist --column "Unblock" --column "Package" --separator "" --print-column=2 --width=600 --height=400; }
check_file() { touch .blocked_packages; }
sanitize_file() { sed '/^$/d' -i .blocked_packages; }
status_dialog_blocked() { yad --title "Blocked packages" --text-info --listen --width=600 --height=400 --button=gtk-ok:0; }
status_dialog_unblocked() { yad --title "Unblocked packages" --text-info --listen --width=600 --height=400 --button=gtk-ok:0; }
disable_packages() {
    # can be done with xargs if you don't like this way
    while IFS= read -r package; do
	if [[ $(os_version) < 5 ]]; then
		adb shell pm block "$package"
		printf "FALSE\n$package\n" >> .blocked_packages
	elif [[ $(os_version) > 5 || $(os_version) = 5 ]]; then
		adb shell pm clear "$package"
		adb shell pm hide "$package"
		printf "FALSE\n$package\n" >> .blocked_packages
	fi
    done
}
enable_packages() {
    # can be done with xargs if you don't like this way
    while IFS= read -r package; do
	if [[ $(os_version) < 5 ]]; then
	        adb shell pm unblock "$package"
	        sed -n '/'$package'/{n;x;d;};x;1d;p;${x;p;}' -i .blocked_packages
	elif [[ $(os_version) > 5 || $(os_version) = 5 ]]; then
                adb shell pm unhide "$package"
                sed -n '/'$package'/{n;x;d;};x;1d;p;${x;p;}' -i .blocked_packages
	fi
    done
}
block() { 
	check_file
	sanitize_file
	get_packages | select_packages_block | disable_packages | status_dialog_blocked
	sanitize_file;
}
unblock() { 
	check_file
	sanitize_file
	cat .blocked_packages | select_packages_unblock | enable_packages | status_dialog_unblocked
	check_file
	sanitize_file; 
}
yad	--image "dialog-question" \
	--title "adb-block" \
	--button=Block:1 \
	--button=Unblock:2 \
	--text "Would you like to block or unblock?"
ret=$?
if [[ $ret == 1 ]]; then
	block
elif [[ $ret == 2 ]]; then
	unblock
elif [[ $ret == 0 ]]; then
	exit
fi
